export const projects = [
  {
    id: 'alfabeto',
    number: '01',
    title: 'Alfabeto Monstruoso',
    category: 'Experiência Criativa',
    date: '1º semestre de 2026',
    kind: 'Projeto da faculdade',
    description: 'Um aplicativo para explorar as letras com imagens, sons e um quiz. Foi desenvolvido na disciplina de Experiência Criativa, durante o primeiro semestre da faculdade.',
    contribution: 'Participei da programação da lógica e das interações do aplicativo, sem usar IA nessa parte. O desafio foi conectar as letras, os sons e as perguntas em uma experiência que fizesse sentido para quem estivesse usando.',
    process: 'Na etapa final, por orientação do professor, usamos IA para melhorar alguns detalhes estéticos. Essa ajuda ficou restrita ao visual do aplicativo.',
    tags: ['Processing', 'Interação', 'Áudio e imagem'],
    status: 'Projeto acadêmico',
    repo: 'https://github.com/GustavoFVilela/semesterOrganizer/tree/main/3.%20criativeProcessing/expcriative_apmm_finalizado',
    ai: 'IA apenas nos ajustes visuais finais, conforme orientação do professor. A lógica foi desenvolvida sem IA.',
  },
  {
    id: 'banco',
    number: '02',
    title: 'Sistema bancário',
    category: 'Lógica de Programação',
    date: '1º semestre de 2026',
    kind: 'Trabalho em grupo',
    description: 'Uma simulação de banco feita em Python para a disciplina de Lógica de Programação. O programa permite consultar saldo, fazer depósitos e saques e acompanhar as transações pelo terminal.',
    contribution: 'Trabalhei com meu grupo na programação e na revisão do código. Minhas contribuições incluem ajustes no acesso do gerente, no controle das tentativas de login e no salvamento dos dados ao sair do programa.',
    process: 'Pratiquei o uso de dicionários, condições e arquivos, além de aprender a trabalhar no mesmo código com outras pessoas. Nosso trabalho recebeu nota máxima.',
    tags: ['Python', 'Lógica', 'Trabalho em equipe'],
    status: 'Nota máxima',
    repo: 'https://github.com/GustavoFVilela/semesterOrganizer/tree/main/4.%20bank%20system',
    ai: 'Desenvolvido em grupo sem uso de inteligência artificial.',
  },
  {
    id: 'commit',
    number: '03',
    title: 'Commit',
    category: 'Aplicativo de organização',
    date: 'Desde setembro de 2026',
    kind: 'Projeto pessoal',
    description: 'Um aplicativo de organização que comecei a criar porque sentia falta de algumas funções nos apps que usava. A ideia é reunir a organização da faculdade e da vida pessoal em um lugar só.',
    contribution: 'O projeto ainda está bem no começo do desenvolvimento. Estou construindo o aplicativo nos horários livres da faculdade, enquanto aprendo JavaScript e React Native. Até agora, implementei a navegação entre as telas e a criação de nomes de pastas durante a sessão.',
    process: 'Uso o Cursor com Grok 4.6 para tirar dúvidas e aprender conceitos e funções enquanto escrevo o código. O próximo passo é salvar os dados e desenvolver as tarefas e o calendário.',
    tags: ['JavaScript', 'React Native', 'Expo'],
    status: 'Em desenvolvimento',
    repo: 'https://github.com/GustavoFVilela/Commit',
    ai: 'Cursor com Grok 4.6 como apoio ao aprendizado: explicações, dúvidas sobre a linguagem e funções. Eu desenvolvo o código enquanto aprendo.',
  },
]
